quarkus.banner.enabled=false
quarkus.log.level=WARN

# Native build configuration
quarkus.native.additional-build-args=--initialize-at-run-time=net.thisptr.jackson.jq
quarkus.native.resources.includes=net/thisptr/jackson/jq/jq.json,META-INF/services/net.thisptr.jackson.jq.Function
